#<<<<<<< HEAD
# Generated by Django 2.2.7 on 2019-12-05 03:34
#=======
# Generated by Django 2.2.7 on 2019-12-05 03:48
#>>>>>>> 1edfb4678404e9d25c8feb9bf4bf3f79021e5147

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate for squirrel sighting point')),
                ('longitude', models.FloatField(help_text='Longitude coordinate for squirrel sighting point')),
                ('unique_id', models.CharField(help_text='Identification tag for each squirrel sighting', max_length=50)),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('other', 'Other')], default='other', help_text='Sighting occurred in the morning or late afternoon', max_length=5)),
                ('date', models.CharField(help_text='Concatenation of the sighting session day and month', max_length=8)),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('other', 'Other')], default='other', help_text='Value is either Adult or Juvenile', max_length=50)),
                ('primary_fur_color', models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black'), ('other', 'Other')], default='other', help_text='Value is either "Gray," "Cinnamon" or "Black."', max_length=50)),
                ('location', models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location of where the squirrel was when first sighted', max_length=50)),
                ('specific_location', models.CharField(help_text='Additional commentary on the squirrel location', max_length=300)),
                ('quaas', models.BooleanField(default=False, help_text='Whether the squirrel was heard quaaing')),
                ('moans', models.BooleanField(default=False, help_text='Whether the squirrel was heard moaning')),
                ('tail_flags', models.BooleanField(default=False, help_text='Whether the squirrel was seen flagging its tail')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Whether the squirrel was seen twitching its tail')),
                ('approaches', models.BooleanField(default=False, help_text='Whether the squirrel was seen approaching human, seeking foodl')),
                ('indifferent', models.BooleanField(default=False, help_text='Whether the Squirrel was indifferent to human presence')),
                ('runs_from', models.BooleanField(default=False, help_text='Whether the Squirrel was seen running from humans, seeing them as a threat')),
                ('running', models.BooleanField(default=False, help_text='Whether squirrel was seen running')),
                ('chasing', models.BooleanField(default=False, help_text='Whether squirrel was seen chasing another squirrel.')),
                ('climbing', models.BooleanField(default=False, help_text='Whether Squirrel was seen climbing a tree or other environmental landmark.')),
                ('eating', models.BooleanField(default=False, help_text='Whether squirrel was seen eating')),
                ('foraging', models.BooleanField(default=False, help_text='Whether squirrel was seen foraging for food')),
                ('other_activities', models.CharField(help_text='Whether squirrel was seen engaged in any other activity', max_length=200)),
                ('kuks', models.BooleanField(default=False, help_text='Whether squirrel was heard kukking')),
            ],
        ),
    ]
