# Generated by Django 2.2.7 on 2019-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_id',
            field=models.CharField(help_text='Identification tag for each squirrel sighting', max_length=50, primary_key=True, serialize=False),
        ),
    ]
